# version: '3.8'

# services:
#   web:
#     build: .
#     # command: python manage.py runserver 0.0.0.0:8000
#     command: gunicorn otpmicroservice.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - ./static:/static
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env

#   nginx:
#     build: ../nginx
#     volumes:
#       - ./static:/backend/static
#     ports:
#       - 443:80
#     depends_on:
#       - web
# volumes:
#   static_volume:
#   media_volume: