# pull official base image
# FROM python:3.9.6-alpine


# # create the appropriate directories
# # ENV HOME=/app
# ENV APP_HOME=/usr/src/otpmicroservice
# WORKDIR $APP_HOME

# # # set work directory
# # WORKDIR /usr/src/otpmicroservice

# # set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# # install system dependencies
# RUN apk add --no-cache python3-dev mariadb-dev build-base

# # install dependencies
# RUN pip install --upgrade pip
# COPY ./requirements.txt .
# RUN pip install -r requirements.txt

# # copy project
# COPY . .